package com.secretchat.mybatis.beans;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 用户信息.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserBean implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户编号. */
	private Integer id;

	/** 用户登录名. */
	private String userName;

	/** 用户昵称. */
	private String nickName;

	/** 用户密码. */
	private String password;

	/** 用户性别. */
	private Integer sex;

	/** 用户电话. */
	private String mobile;

	/** 最后登录时间 **/
	private String loginTime;

	/** 最后登录IP **/
	private String loginIP;

	/** 用户邮箱. */
	private String email;

	/** 用户名称. */
	private String trueName;

	/** 创建时间. */
	private String regTime;

	/** 创建ip. */
	private String regIP;

	/** 用户类型 */
	private String userType;

	/** 用户生日. */
	private Date birthDay;

	/** 用户身份证. */
	private String iDCard;

	/** 状态 0正常 1. */
	private Integer status;

	/** 真实头像. */
	private String headPic;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getLoginTime() {
		return loginTime;
	}

	public void setLoginTime(String loginTime) {
		this.loginTime = loginTime;
	}

	public String getLoginIP() {
		return loginIP;
	}

	public void setLoginIP(String loginIP) {
		this.loginIP = loginIP;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTrueName() {
		return trueName;
	}

	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

	public String getRegTime() {
		return regTime;
	}

	public void setRegTime(String regTime) {
		this.regTime = regTime;
	}

	public String getRegIP() {
		return regIP;
	}

	public void setRegIP(String regIP) {
		this.regIP = regIP;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Date getBirthDay() {
		return birthDay;
	}

	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	public String getiDCard() {
		return iDCard;
	}

	public void setiDCard(String iDCard) {
		this.iDCard = iDCard;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getHeadPic() {
		return headPic;
	}

	public void setHeadPic(String headPic) {
		this.headPic = headPic;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
